# Generated by Django 5.0.6 on 2024-06-18 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_level_topic_user_question_level_topic_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Programmer",
        ),
    ]
